name: Java CI (No Maven, with Servlet API)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Servlet API
        run: |
          mkdir -p lib
          curl -o lib/jakarta.servlet-api.jar https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar

      - name: Compile Java files
        run: |
          mkdir -p build
          find src/main/java -name "*.java" > sources.txt
          javac -cp "lib/jakarta.servlet-api.jar" -d build @sources.txt

      - name: Upload compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: build
